### ISSUE TITLE
Unexpected Token %

### ISSUE THREAD

**Issue by a75c6** [Alhadis/Record-Jar#1]
I receive the following error when trying to run the basic example:

```
%%
^

SyntaxError: Unexpected token %
```

**Comment by Alhadis** [comment]
Erh, what exactly is your code?

From that error message alone, it seems as though you're trying to execute a record-jar's data as JavaScript source...

**Comment by a75c6** [comment]
```
const load = require('load')
const data = load("languages01.txt")


var jar  = new RecordJar(data);


for(var i = 0; i < jar.records.length; ++i){
	console.log( jar.records[i] );
}
```

**Comment by a75c6** [comment]
My goal is to take the IANA subtag registry found here:

https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

And create a single json file that has all the subvalues as the key and the description as the value:

```
{
	"aa": "Afar",
	"ab": "Abkhazian"
}
```

**Comment by Alhadis** [comment]
It's because of the [`load`](https://www.npmjs.com/package/load) module that you're using. Going by its readme, it just seems to be some weird alternative to using Node's `require` function.

You should be using [`fs.readFile`](https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback) or [`fs.readFileSync`](https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options) instead:

~~~js
const fs = require("fs");
const data = fs.readFileSync("languages01.txt").toString();
~~~

**Comment by Alhadis** [comment]
@namsoila If you're still having troubles, please be sure to let me know.
